name: codelint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  codelint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: install dependencies
        run: pnpm install

      - name: print versions
        run: |
          node --version
          pnpm --version
          pnpm exec astro --version
          pnpm exec eslint --version
          pnpm exec stylelint --version
          pnpm exec markdownlint --version
          pnpm exec prettier --version

      - name: run astro type checking and diagnostics
        run: pnpm check:astro

      - name: validate javascript and typescript
        run: pnpm check:js

      - name: validate css
        run: pnpm check:css

      - name: validate markdown
        run: pnpm check:md

      - name: validate code formatting
        run: pnpm check:format
