name: commitlint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: install commitlint
        run: pnpm install -D @commitlint/cli @commitlint/config-conventional

      - name: print versions
        run: |
          git --version
          node --version
          pnpm --version
          pnpm exec commitlint --version

      - name: validate last commits
        if: github.event_name == 'push'
        run:
          pnpm exec commitlint --from ${{ github.event.before }} --to ${{
          github.event.after }} --verbose

      - name: validate pr commits
        if: github.event_name == 'pull_request'
        run:
          pnpm exec commitlint --from ${{ github.event.pull_request.base.sha }}
          --to ${{ github.event.pull_request.head.sha }} --verbose
